=== MilanKosticKIT/Rechneruebung_4/rechneraufgabe_3_schema.xsd
<?xml  version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rechnungssammlung">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rechnung" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="leistungssteller" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="adresse">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="strasse" type="xs:string"/>
                                                    <xs:element name="hausnummer" type="xs:string"/>
                                                    <xs:element name="postleitzahl" type="xs:int"/>
                                                    <xs:element name="ort" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="telefon" type="xs:string"/>
                                        <xs:element name="fax" type="xs:string"/>
                                        <xs:element name="e-mail" type="xs:string"/>
                                        <xs:element name="steuernummer" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="leistungsempfaenger">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="anrede" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="adresse">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="strasse" type="xs:string"/>
                                                    <xs:element name="hausnummer" type="xs:string"/>
                                                    <xs:element name="postleitzahl" type="xs:int"/>
                                                    <xs:element name="ort" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="rechnungsdatum" type="xs:string"/>
                            <xs:element name="rechnungsnummer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]([0-9/ \-])+[0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dienstleistungen">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dienstleistung" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="position" type="xs:int"/>
                                                    <xs:element name="menge-oder-umfang" type="xs:string"/>
                                                    <xs:element name="art-der-dienstleistung" type="xs:string"/>
                                                    <xs:element name="einzelpreis">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="betrag" type="xs:decimal"/>
                                                                <xs:element name="waehrung" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="gesamtpreis">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="betrag" type="xs:decimal"/>
                                                                <xs:element name="waehrung" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="mwst" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="datum" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="kosten">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="steuerbetrag">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="betrag" type="xs:decimal"/>
                                                    <xs:element name="waehrung" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="entgeld">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="betrag" type="xs:decimal"/>
                                                    <xs:element name="waehrung" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="nettobetrag">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="betrag" type="xs:decimal"/>
                                                    <xs:element name="waehrung" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="zahlungsmoeglichkeiten">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bankverbindung" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:choice>
                                                    <xs:sequence>
                                                        <xs:element name="IBAN" type="xs:string"/>
                                                        <xs:element name="BIC" type="xs:string" minOccurs="0"/>
                                                    </xs:sequence>
                                                    <xs:sequence>
                                                        <xs:element name="BLZ" type="xs:positiveInteger"/>
                                                        <xs:element name="Kontonummer" type="xs:positiveInteger"/>
                                                        <xs:element name="Bank" type="xs:string" minOccurs="0"/>
                                                    </xs:sequence>
                                                    <xs:sequence>
                                                        <xs:element name="BitcoinAdresse" type="xs:string"/>
                                                    </xs:sequence>
                                                    <xs:sequence>
                                                        <xs:element name="BIC" type="xs:string"/>
                                                        <xs:element name="Kontonummer" type="xs:positiveInteger"/>
                                                    </xs:sequence>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MilanKosticKIT/Rechneruebung_4/rechneraufgabe_4_rechnungssammlung.xml
<?xml  version="1.0" encoding="utf-8"?>
<rechnungssammlung
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rechneraufgabe_3_schema.xsd">
    <rechnung>
        <leistungssteller>
            <name>Rochade-La Hoff Pharma GmbH</name>
            <adresse>
                <strasse>An der Chemie</strasse>
                <hausnummer>17</hausnummer>
                <postleitzahl>79639</postleitzahl>
                <ort>Grenzych-Wahlen</ort>
            </adresse>
            <telefon>07624&#47;666 333 999</telefon>
            <fax>07624&#47;666 333 990</fax>
            <e-mail></e-mail>
            <steuernummer>88 123&#47;82822</steuernummer>
        </leistungssteller>
        <leistungsempfaenger>
            <anrede>Dr. med.</anrede>
            <name>Cyprian Zottel</name>
            <adresse>
                <strasse>Soddelstrudel</strasse>
                <hausnummer>5a</hausnummer>
                <postleitzahl>13023</postleitzahl>
                <ort>Zotenheim</ort>
            </adresse>
        </leistungsempfaenger>
        <rechnungsdatum>8.8.2017</rechnungsdatum>
        <rechnungsnummer>98-798-7987</rechnungsnummer>
        <dienstleistungen>
            <dienstleistung datum="">
                <position>1</position>
                <menge-oder-umfang>3 Packungen</menge-oder-umfang>
                <art-der-dienstleistung>Grippemittel "Tumifla"</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>120</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>360</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
            <dienstleistung datum="">
                <position>2</position>
                <menge-oder-umfang></menge-oder-umfang>
                <art-der-dienstleistung>Beratung pauschal</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>50</betrag>
                    <waehrung></waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>50</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
            <dienstleistung datum="">
                <position>3</position>
                <menge-oder-umfang>2 Liter</menge-oder-umfang>
                <art-der-dienstleistung>Abf&#252;hrmittel "Wech damit"</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>99.99</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>199.98</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
            <dienstleistung datum="">
                <position>4</position>
                <menge-oder-umfang>2 St&#252;ck</menge-oder-umfang>
                <art-der-dienstleistung>Energieriegel "Satto"</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>5.98</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>11.96</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>7</mwst>
            </dienstleistung>
        </dienstleistungen>
        <kosten>
            <steuerbetrag>
                <betrag>116.74</betrag>
                <waehrung>€</waehrung>
            </steuerbetrag>
            <entgeld>
                <betrag>621.94</betrag>
                <waehrung>€</waehrung>
            </entgeld>
            <nettobetrag>
                <betrag>490.22</betrag>
                <waehrung>€</waehrung>
            </nettobetrag>
        </kosten>
        <zahlungsmoeglichkeiten>
            <bankverbindung>
                <BLZ>66050101</BLZ>
                <Kontonummer>987654321</Kontonummer>
                <Bank>Sparkasse Karlsruhe</Bank>
            </bankverbindung>
        </zahlungsmoeglichkeiten>
    </rechnung>
    <rechnung>
        <leistungssteller>
            <name>Kleintier Meier GmbH</name>
            <adresse>
                <strasse>Meierring</strasse>
                <hausnummer>3</hausnummer>
                <postleitzahl>81828</postleitzahl>
                <ort>Machthausen</ort>
            </adresse>
            <telefon>0777&#47;987987</telefon>
            <fax>0777&#47;987789</fax>
            <e-mail>klein.meier&#64;tiere.de</e-mail>
            <steuernummer>88123&#47;82822</steuernummer>
        </leistungssteller>
        <leistungsempfaenger>
            <anrede>Frau</anrede>
            <name>Sybille Sonder-Suttelrau</name>
            <adresse>
                <strasse>Am S&#252;ttelbach</strasse>
                <hausnummer>17</hausnummer>
                <postleitzahl>77070</postleitzahl>
                <ort>Siedelsuderstadt</ort>
            </adresse>
        </leistungsempfaenger>
        <rechnungsdatum>15.1.2017</rechnungsdatum>
        <rechnungsnummer>657321</rechnungsnummer>
        <dienstleistungen>
            <dienstleistung datum="1.1.2017">
                <position>1</position>
                <menge-oder-umfang>100</menge-oder-umfang>
                <art-der-dienstleistung>Antike Holzw&#252;rmer</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>1.5</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>150</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
            <dienstleistung datum="12.1.2017">
                <position>2</position>
                <menge-oder-umfang>1</menge-oder-umfang>
                <art-der-dienstleistung>Holzwurmfetter</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>34.45</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>34.45</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
            <dienstleistung datum="12.1.2017">
                <position>3</position>
                <menge-oder-umfang>1</menge-oder-umfang>
                <art-der-dienstleistung>Steinlaus,Petrophaga lorioti</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>777.77</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>777.77</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst>19</mwst>
            </dienstleistung>
        </dienstleistungen>
        <kosten>
            <steuerbetrag>
                <betrag>153.63</betrag>
                <waehrung>€</waehrung>
            </steuerbetrag>
            <entgeld>
                <betrag>962.22</betrag>
                <waehrung>€</waehrung>
            </entgeld>
            <nettobetrag>
                <betrag>808.59</betrag>
                <waehrung>€</waehrung>
            </nettobetrag>
        </kosten>
        <zahlungsmoeglichkeiten>
            <bankverbindung>
                <IBAN>DE18 6837 0034 0999 6663 3</IBAN>
                <BIC>DEUTDE6F683</BIC>
            </bankverbindung>
        </zahlungsmoeglichkeiten>
    </rechnung>
    <rechnung>
        <leistungssteller>
            <name>Bestattungen Unterberg</name>
            <adresse>
                <strasse>Oberweg</strasse>
                <hausnummer>5</hausnummer>
                <postleitzahl>43210</postleitzahl>
                <ort>Ultursingen</ort>
            </adresse>
            <telefon>0478&#47;777555</telefon>
            <fax></fax>
            <e-mail>unter&#64;</e-mail>
            <steuernummer>DE 987654321</steuernummer>
        </leistungssteller>
        <leistungsempfaenger>
            <anrede>Famile</anrede>
            <name>Urmel</name>
            <adresse>
                <strasse>Ulturenstrasse</strasse>
                <hausnummer>764</hausnummer>
                <postleitzahl>43210</postleitzahl>
                <ort>Ultursingen</ort>
            </adresse>
        </leistungsempfaenger>
        <rechnungsdatum>19.10.17</rechnungsdatum>
        <rechnungsnummer>893 213 11</rechnungsnummer>
        <dienstleistungen>
            <dienstleistung>
                <position>1</position>
                <menge-oder-umfang>1</menge-oder-umfang>
                <art-der-dienstleistung>Urne, Eiche massiv</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>299.99</betrag>
                    <waehrung>€</waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>299.99</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst></mwst>
            </dienstleistung>
            <dienstleistung>
                <position>2</position>
                <menge-oder-umfang>1</menge-oder-umfang>
                <art-der-dienstleistung>&#220;berf&#252;hrung Krematorium Feuerbach inkl. Begleitpersonal</art-der-dienstleistung>
                <einzelpreis>
                    <betrag>349.00</betrag>
                    <waehrung></waehrung>
                </einzelpreis>
                <gesamtpreis>
                    <betrag>349.00</betrag>
                    <waehrung>€</waehrung>
                </gesamtpreis>
                <mwst></mwst>
            </dienstleistung>
            <dienstleistung>
